/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_softtanck_tanck_aes_utils_AesUtils */

#ifndef _Included_com_softtanck_tanck_aes_utils_AesUtils
#define _Included_com_softtanck_tanck_aes_utils_AesUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_softtanck_tanck_aes_utils_AesUtils
 * Method:    Encrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_softtanck_tanck_aes_utils_AesUtils_Encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_softtanck_tanck_aes_utils_AesUtils
 * Method:    Decrypt
 * Signature: ([B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_com_softtanck_tanck_aes_utils_AesUtils_Decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
